# Generated by Django 5.1.2 on 2025-02-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
