# Generated by Django 5.1.2 on 2025-02-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_product_is_sponsored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
    ]
