# Generated by Django 5.1.2 on 2025-02-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_created_at_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.seller'),
        ),
    ]
