# Generated by Django 5.1.2 on 2025-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('SERVICE_PROVIDER', 'Service Provider'), ('NORMAL_USER', 'Normal user')], max_length=20),
        ),
    ]
