# Generated by Django 5.1.2 on 2025-02-26 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_sellers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seller',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
