# Generated by Django 5.1.2 on 2025-03-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupstation',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
