# Generated by Django 5.1.2 on 2025-03-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_pickupstation_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
