# Generated by Django 5.1.2 on 2025-03-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_order_delivery_end_date_order_delivery_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
