# Generated by Django 5.1.2 on 2025-03-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_transaction_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='delivery_date',
        ),
    ]
